### PR TITLE
Add elevated indicator

### PR DESCRIPTION
**Pull request by zpqrtbnk**

### CODE REVIEW

**Comment by zpqrtbnk** [comment]
This is for issue #11

**Comment by mayerwin** [comment]
Thanks a lot for the PR. I'll think a bit more about this before possibly merging. I want to avoid having to remove a feature later that would break retro-compatibility (and not have a feature bloat either).
Have you been able to compile for your own use in the meantime?

**Comment by zpqrtbnk** [comment]
Yes it builds and that's what I am running now so I can see "MyProject (ADMINISTRATOR)" in the title bar. Totally understand you want to think about it, though.

**Comment by mayerwin** [comment]
[elevationSuffix] tag added in the 3.4.0 release.

**Pull request closed without merging**
