### PR TITLE
Added support for [documentPath] tag

### PR DESCRIPTION
**Pull request by Wimpje**
- I have a lot of similar file names in the same solution/project, but different file paths, this makes it easier to see where I'm at.

### CODE REVIEW

**Comment by mayerwin** [comment]
Thanks a lot for the PR. I'll review and merge it in the next release if all looks good. This is indeed a feature that has been requested a few times.

**Comment by Wimpje** [comment]
Yeah, good idea, I don't have time the coming week, but I'll take a look afterwards if I can add that too.

**Comment by mayerwin** [comment]
Fyi, I have also implemented "documentPath:X", "documentPath:X:Y", "documentParentPath:X", "documentParentPath:X:Y" and released version 3.3.0 (hopefully bug-free).

Thanks for your contribution.

**Comment by Wimpje** [comment]
Cool! Thanks! I'll update right away :)

**Pull request merged**
