### PR TITLE
Cleaning up the startupProjectNames. Removing relative path from the …

### PR DESCRIPTION
**Pull request by xScooper**
…name if it is present.

UE4 example:
"Intermediate\ProjectFiles\MyGame.vcxproj" will now become "MyGame" instead of "Intermediate\ProjectFiles\MyGame".

### CODE REVIEW

**Comment by mayerwin** [comment]
Thanks! I am just not sure if this is what most people would expect (since the relative path can be considered as important information)? 

I hesitate changing the current behavior with your PR and adding `[startupProjectNamesWithRelativePath]` (if you think of a better name let me know) for the current behavior, or adding a `[startupProjectNamesWithRelativePath]` with your PR.

**Comment by xScooper** [comment]
I was thinking about the same thing, so I'd be perfectly fine with having this be a separate keyword.

I personally decided against it because the behavior I expected with `startupProjectNames` was just the project name as seen in the solution explorer. And instead it included the relative path. Which for Unreal Engine 4 projects at the very least just adds noise.

Let me know if there's anything else I can do to help with this specific issue.

**Comment by xScooper** [comment]
@mayerwin I've split the new functionality into its own new keyword now. So the original functionality stays unchanged, while the new "NonRelative" method is now available for those who want it.

What do you think of this one instead?

**Comment by mayerwin** [comment]
Perfect, thanks! I'll push this to the marketplace within the next hour and credit you for the help if you don't mind.

**Comment by xScooper** [comment]
Sounds good :)

**Pull request merged**
